[package]
name = "drs"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.9", features = ["macros"] }
tokio = { version = "1.53.1", features = ["full"] }
tower = { version = "0.5", features = ["util"] }
http-body-util = "0.1"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
rust-bert = "0.23"
tch = "0.17"
anyhow = "1.0"
helpers = { version = "0.1.0", path = "../helpers" }
model = { version = "0.1.0", path = "../model" }
serde = "1.0.229"
serde_json = "1.0.151"

[dependencies.torch-sys]
version = "*"
features = ["download-libtorch"]
